steps:
- name: 'gcr.io/cloud-builders/gcloud'
  script: |
    gcloud run deploy cloudrunservice --image us-docker.pkg.dev/cloudrun/container/hello --region us-central1 --platform managed --allow-unauthenticated

options:
  substitution_option: 'ALLOW_LOOSE'
  dynamic_substitutions: true

substitutions:
  _REPOSITORY: 'container'
  _SERVICE_NAME: 'hello'
  _TAG: 'latest'
  _REGION: 'us'  # Default value, can be overridden
  _IMAGE_NAME: '${_REGION}-docker.pkg.dev/cloudrun/${_REPOSITORY}/${_SERVICE_NAME}:${_TAG}'
