steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud run deploy cloudrunservice \
    --image ${_IMAGE_NAME} \
    --region ${_REGION} \
    --platform managed \
    --allow-unauthenticated

options:
  substitution_option: 'ALLOW_LOOSE'
  dynamic_substitutions: true

substitutions:
  _REPOSITORY: 'container'
  _SERVICE_NAME: 'hello'
  _TAG: 'latest'
  _REGION: 'us-central1'  # Default value, can be overridden
  _IMAGE_NAME: 'us-docker.pkg.dev/cloudrun/${_REPOSITORY}/${_SERVICE_NAME}:${_TAG}'
